### ISSUE TITLE
Infraorder and genera in checklist

### ISSUE THREAD

**Issue by LienReyserhove** [trias-project/alien-herpetofauna-belgium#1]
The checklist includes one record at the infraorder level and several genera. For these scientific names, the format is now e.g. 
 `Gekkota spec. (...)` or `Phyton spec. (...)`  I wonder if we can leave out the `spec.` 

Additionally, it seems a bit odd to me to include species like `Phyton molurus (...)` and `Phyton regius (...)`, followed by the general genus `Phyton (...)`. What is the reason for this?

**Comment by peterdesmet** [comment]
Yes, I think we should leave out `spec.` when mapping. I'll let @timadriaens answer the second question.

**Comment by timadriaens** [comment]
yes, think we can leave out the spec. but not the specific species P. molurus and P. regius of course.

**Comment by peterdesmet** [comment]
Nah, the question was: should we leave in genera record, if species are also defined?

**Comment by timadriaens** [comment]
I can find 19 of those, and for me the answer is yes actually, at least for the genera ones... (higher taxa I don't know)

Calotes   spec. (Cuvier, 1817)
Pogona   spec. (Storr, 1982)
Apalone   spec. (Rafinesque, 1832)
Pogona   spec. (Storr, 1982)
Boa   spec. (Linnaeus, 1758)
Lampropeltis   spec. (Fitzinger, 1843)
Thamnophis   spec. (Fitzinger, 1843)
Sistrurus   spec. (Garman, 1884)
Anolis   spec. (Daudin, 1802)
Hemidactylus   spec. (Oken, 1817)
Pachydactylus   spec. (Wiegmann, 1834)
Phelsuma   spec. (Gray, 1825)
Iguana   spec. (Laurenti, 1768)
Boaedon   spec. (Duméril, Bibron and Duméril, 1854)
Rhamphiophis   spec. (Peters, 1854)
Python   spec. (Daudin, 1803)
Gekkota   spec. (Cuvier, 1817)
Mauremys   spec. (Gray, 1869)
Testudo   spec. (Linnaeus, 1758)

**Comment by LienReyserhove** [comment]
OK, so I conclude:

- leave out `spec`
- Do not remove the genera from the checklist, even if species within that genus are also defined.

For `Gekkota spec.`, the taxon rank is infraorder, but I assume the same rule can be applied here, i.e. keep the record?

**Comment by timadriaens** [comment]
I think so yes, keep the record. We should include Loïc in these discussions probably.

**Comment by timadriaens** [comment]
although I think it is more clear to keep the spec. actually, why do you want them out? I means simply: we know if was a species of Pÿthon, and it was not identified to species level.

**Comment by LienReyserhove** [comment]
I contacted Loïc for his GitHub user name, couldn't find him , so I will include him as soon as I have the information (or please do if you already have this information)

**Comment by LienReyserhove** [comment]
@timadriaens my main reason is the match with the GBIF backbone. If you match `Python spec. (...)` with the GBIF backbone it returns the higher rank, the genus `Python (...)`.

So I guess it doesn't recognize `Python spec.` as a genus but it considers the record to be an unknown species. (@peterdesmet please correct me if I'm wrong)

**Comment by peterdesmet** [comment]
@LienReyserhove that might be the case indeed. It is more that a "Python spec." is an identification: "I'm not sure what species, but it is a Python species". In checklists there are no identifications, just taxa, so it's better to use "Python": The genus Python is non-native in Belgium.

**Comment by LienReyserhove** [comment]
@timadriaens @LoicvanDoornINBO Can we decide on this issue, see also the previous comment by @peterdesmet

**Comment by timadriaens** [comment]
Yes, we can. I would propose we keep the genus Python then as a separate record (so the spec. becomes a checklist record at the genus level) on top of the Python species that were identified to species level. Of course, this is not a solution for genera that have both non-native ánd native species in Belgium but in this case for herptiles it works well.
