### ISSUE TITLE
Chrysemys picta subsp. Bellii (Gray, 1831) and other subspecies

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/alien-herpetofauna-belgium#10]
`Chrysemys picta subsp. Bellii (Gray, 1831)` is not recognized by the GBIF backbone taxonomy, because `Bellii` is written with capital B. `bellii` does match: https://api.gbif.org/v1/species/match?strict=true&name=Chrysemys%20picta%20subsp.%20bellii%20(Gray,%201831)

Note also that `subsp.` is reserved for plant and fungi names, to distinguish from `var.` and `forma`. Animal names only allow subspecies and these names should be written as `Chrysemys picta bellii`

- [x] Correct `Bellii` to `bellii`
- [x] Remove `subsp.` from names: Graptemys pseudogeographica subsp. kohnii (Baur, 1890), Graptemys pseudogeographica subsp. pseudogeographica (Gray, 1831), Chrysemys picta subsp. Bellii (Gray, 1831)
- [ ] Remove the duplicate `Chrysemys picta subsp. Bellii (Gray, 1831)`,  since the name appears twice (line 12 and 101 at https://github.com/trias-project/alien-herpetofauna-belgium/blob/main/data/raw/alien-herpetofauna-checklist_dump.csv#L101)
- [x] Remove `Chrysemys picta subsp. Bellii (Gray, 1831)` from ad hoc checklist now that it appears here? It is also written incorrectly there.

**Comment by LienReyserhove** [comment]
Thx for the input. Two remarks:

- The duplicate `Chrysemys picta subsp. Bellii (Gray, 1831)` is not an error. These are two records describing the distribution of the species on different regions, one in Flanders and one in Brussels. 

- I didn't find that specific record in the ad hoc checklist, so I assume it has already been removed?
