### ISSUE TITLE
Infraorder Gekkota (Cuvier, 1817)

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/alien-herpetofauna-belgium#11]
Gekkota (Cuvier, 1817) is an infraorder. Note that infraorders are not used by the GBIF backbone taxonomy and as a result, this taxon will not appear in the unified checklist (since there is no match). Is there a way to choose a higher/lower level for Geckos?

Note also that `Gekkota spec (Cuvier, 1817)` appears on the ad hoc checklist. Should it be removed there?

**Comment by LienReyserhove** [comment]
We already had this discussion in #1 
The decision was that we should keep them in. Should I reopen the issue?

**Comment by sannegovaert** [comment]
Loïc: OK if it is not in the unified list.
