### ISSUE TITLE
Pathway missing prefix "cbd_2014_pathway:"

### ISSUE THREAD

**Issue by damianooldoni** [trias-project/alien-herpetofauna-belgium#14]
As found in https://github.com/trias-project/unified-checklist/issues/69, I think the prefix should be added during the mapping of this checklist. I think the problem is in [dwc_mapping.Rmd#L437](https://github.com/trias-project/alien-herpetofauna-belgium/blob/main/src/dwc_mapping.Rmd#L437).

**Comment by LienReyserhove** [comment]
Done, see #18
