### ISSUE TITLE
Not standard pathway type

### ISSUE THREAD

**Issue by damianooldoni** [trias-project/alien-herpetofauna-belgium#15]
In description extension, we were used to have pathway information stored with `type` equal to `pathway`. In this checklist such information is stored with `type` equal to `introduction pathway` as I found while extracting information from the unified (see https://github.com/trias-project/unified-checklist/issues/68).  I think this is very easy to solve in [dwc_mapping.Rmd#L443](https://github.com/trias-project/alien-herpetofauna-belgium/blob/main/src/dwc_mapping.Rmd#L443) by replacing it with:

```r
introduction_pathway %<>% mutate(type = "pathway") 
```

Nothing else should be changed, I think.

**Comment by LienReyserhove** [comment]
See PR #18
