### ISSUE TITLE
non standard description values

### ISSUE THREAD

**Issue by damianooldoni** [trias-project/alien-herpetofauna-belgium#16]
This way to write description values is not tidy and is not the same as done in all other checklists published by TriAS and used for generating the unified checklist. 

An example description `escape_pet | release_other`: https://github.com/trias-project/alien-herpetofauna-belgium/blob/main/data/processed/description.csv#L3

In my opinion, this line should be split in two different rows.

I find quite difficult to write a patch for this bug while working on unified checklist data. High priority to this issue, if possible. Thanks.

**Comment by LienReyserhove** [comment]
See #18
