### ISSUE TITLE
wrong pathway value contaminant | nursery

### ISSUE THREAD

**Issue by damianooldoni** [trias-project/alien-herpetofauna-belgium#17]
I think `contaminant | nursery` should be replaced by `contaminant_nursery` as `nursery` is a pathway level 2 within `contaminant`. @LienReyserhove: am I right?

**Comment by LienReyserhove** [comment]
agree!

**Comment by LienReyserhove** [comment]
I didn't find any `contaminant | nursery` in the checklist so I assume this has already been adapted?

**Comment by sannegovaert** [comment]
Fixed by Tim as mentioned here: https://github.com/trias-project/indicators/issues/97
