### ISSUE TITLE
Date of last observation without date of first observation

### ISSUE THREAD

**Issue by LienReyserhove** [trias-project/alien-herpetofauna-belgium#2]
For two records, there's a date of last observation, but no date of first observation. I wonder why?
- `Pelophylax cf bedriagae` (Wallonia): last observation = 2020
- `Pelophylax ridibundus (Pallas, 1771)` (Wallonia): last observation = 2020

**Comment by LoicvanDoornINBO** [comment]
The Wallonia data is fragmentary. They know these species are currently present, but have no idea when they arrived.
