### ISSUE TITLE
References in source field

### ISSUE THREAD

**Issue by LienReyserhove** [trias-project/alien-herpetofauna-belgium#3]
In the raw data file, references to the source information is included in the field `source`. I have two questions:
- At the moment the source information is added as a **hyperlink** (clickable link). I cannot extract the link in Rstudio, so please provide the **link** and not the hyperlink. Please separate links with a pipe `|` (as is done now for the hyperlinks, which is great)
- More technical: I assume the source information can be added to the taxon core, the distribution extension and the description extension? (species profile extension has no source field, apparently) (@timadriaens)

**Comment by timadriaens** [comment]
how to do that? Just select and remove hyperlink?

**Comment by LienReyserhove** [comment]
Ye, I'm afraid that you will have click each hyperlink, select "Edit link", copy the specific link, and replace the hyperlink with the actual link. Unless there's another, more elegant way to do this, but I'm not aware of any.

**Comment by timadriaens** [comment]
it's OK, I have done that and provided the full URL. Also for the other hyperlinks (to the gbif dataset and some articles). It should be ok now. Problem with the newspaper articles is of course that those links disappear at some point.

**Comment by LienReyserhove** [comment]
thx for the adaptations! I agree with the links to the newspaper, but I don't think it's problematic in this case, as many other sources in this checklist don't have a link, so I would keep it at `news article`
