### ISSUE TITLE
Raw data file: changed .xlsx to gsheet format

### ISSUE THREAD

**Issue by LienReyserhove** [trias-project/alien-herpetofauna-belgium#4]
For your information, I changed the format of the raw data file from a `.xlsx` file to a `.gsheet` format.
I assume that the raw data file will be a dynamic document with new information coming now and then. By using a google sheet format I can easily import the raw data file from the GDrive. If we use a .xlsx format, I have to make a copy in the raw data folder on GitHub, which makes it more complex.
If you don't agree with this approach, I will change it back to an .xlsx format, I didn't remove it yet before I got your feedback.

**Comment by peterdesmet** [comment]
Great! Use the publish as csv approach to then `read_csv()` the data.

**Comment by timadriaens** [comment]
ok!

**Comment by LoicvanDoornINBO** [comment]
ok
