### ISSUE TITLE
Typo's in scientific names?

### ISSUE THREAD

**Issue by LienReyserhove** [trias-project/alien-herpetofauna-belgium#5]
I wonder if the following scientific names are wrong due to typo's and should be corrected?
- Elaphe qua**t**uorlineata (Lacépède, 1987) to Elaphe qua**tt**uorlineata Buseke, 1982
- Sternother**n**us carinatus (Gray, 1856) to Sternotherus carinatus (Gray, 1856)

I'm quite sure the following scientific names can be corrected to:
- Pogona **H**enrylawsoni (Wells and Wellington, 1985) to Pogona **h**enrylawsoni (Wells and Wellington, 1985)
- Gekko **G**ecko to Gekko **g**ecko

(Last two scientific names are already corrected)

**Comment by LoicvanDoornINBO** [comment]
Elaphe qua**t**uorlineata is ok. Other three names are indeed incorrect.

**Comment by LienReyserhove** [comment]
Ok, thx for the input!
