### ISSUE TITLE
Duplicated distribution information

### ISSUE THREAD

**Issue by LienReyserhove** [trias-project/alien-herpetofauna-belgium#6]
In some cases, the information on `native range`, `introduction pathway` and `degree of establishment` in the description extension is duplicated  for a single species. The reason for this is that a single species can have two or three records in the main checklist: one for Flanders, one for Wallonia and/or one for Brussels Capital Region. 

Example:

scientific name | locality | degree of establishment |  introduction pathway 
--- | --- | --- | ---
Boa constrictor (Linnaeus, 1758) | Flanders | casual | escape_pet / release_other
Boa constrictor (Linnaeus, 1758) | Wallonia | casual | escape_pet / release_other

For each of these records, the `native range` information must be the same. I suppose that `introduction pathway` and `degree of establishment` could vary between these records, but this is not the case for this specific checklist. This results in a lot of duplicated information in the description extension, see example below.

taxonID | description | type
--- | --- | ---
taxonID_aabbcc | introduction pathway | escape_pet / release_other
taxonID_aabbcc | introduction pathway | escape_pet / release_other
taxonID_aabbcc | degree of establishment | casual
taxonID_aabbcc | degree of establishment | casual

 I have two suggestions to solve this:

1: **Remove all duplicated information, the information is general for the species in Belgium**

taxonID | description | type
--- | --- | ---
taxonID_aabbcc | introduction pathway | escape_pet / release_other
taxonID_aabbcc | degree of establishment | casual

2: **Keep all duplicated information, and mention the specific locality:**

taxonID | description | type
--- | --- | ---
taxonID_aabbcc | introduction pathway (Flanders) | escape_pet / release_other
taxonID_aabbcc | introduction pathway (Wallonia) | escape_pet / release_other
taxonID_aabbcc | degree of establishment (Flanders) | casual
taxonID_aabbcc | degree of establishment (Wallonia) | casual

For obvious reasons I prefer option 1
@timadriaens
@LoicVanDoornINBO

**Comment by timadriaens** [comment]
we should probably deal with this the same way as for other checklists. How is that done there e.g. in the manual of alien plants or any of the others?

**Comment by LienReyserhove** [comment]
For the manual of plants, we don't have this problem as distribution information is contained in a single line.
For the ad hoc checklist, we ignore the multiple distribution lines (see [this code](https://github.com/trias-project/ad-hoc-checklist/blob/cb63ddad1c9bd537326d292e9d29a95bd3b6fc57/src/dwc_mapping.Rmd#L558-L559)), same as my first suggestion.

**Comment by timadriaens** [comment]
OK, yes, makes sense. Let's go for option 1.
