### ISSUE TITLE
Different information on native range for same species

### ISSUE THREAD

**Issue by LienReyserhove** [trias-project/alien-herpetofauna-belgium#7]
In line with the previous issue (#6 ), I assume that the information on native ranges for a single species should be the same for records in Flanders and Wallonia (i.e. irrespective of the locality where it was found). However, this is not always the case for the following species:

scientific name | locality | native range
--- | --- | ---
Podarcis muralis (Laurenti, 1768) | Brussels | Europe
Podarcis muralis (Laurenti, 1768) | Flanders | Europa / Asia
Tarentola mauritanica (Linnaeus, 1758) | Flanders | Europe / Asia
Tarentola mauritanica (Linnaeus, 1758) | Wallonia | Europe / Africa
Xenopus laevis (Daudin, 1802) | Flanders | Africa / introduced elsewhere
Xenopus laevis (Daudin, 1802) | Wallonia | Africa

@timadriaens @LoicvanDoornINBO can you check this please?

**Comment by timadriaens** [comment]
Tarentola mauritanica should be Europe / Africa 
Podarcis muralis should be Europe
Xenopus laevis should be Africa (European frogs come from South Africa, see [this paper](https://peerj.com/articles/1659.pdf))
