### ISSUE TITLE
Mapping of remarks

### ISSUE THREAD

**Issue by LienReyserhove** [trias-project/alien-herpetofauna-belgium#8]
The field `remarks` in the [raw dataset](https://docs.google.com/spreadsheets/d/1AK68tBlXoplUcI4CfACNlz6mYfrBZodsGu5Lk59BuX0/edit#gid=0) includes information on the introduction pathway (6 records), the place where the species was found (3 records) or the management of the species (1 record). Information on the introduction pathway should be mapped in de description extension, the information on the location in the distribution extension. However, to keep it simple, I would prefer to map all information from the `remarks` field in the raw data to the  `occurrenceRemarks` field from the distribution extension. The description extension has no remarks field, which makes it difficult to put remarks there.   @peterdesmet @timadriaens what do you think?

**Comment by timadriaens** [comment]
I have taken a look, the information in the remarks field is just additional to the already filled information on pathways etc. So no problem for me to leave it as is in the occurrenceRemarks of the distribution extension.
